#!/usr/bin/env python3
"""Run contract tests and generate the manuscript MCTS consistency audit."""

from __future__ import annotations

import argparse
import io
import sys
import unittest
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from mcts.config import load_config, validate_manuscript_config  # noqa: E402


CHECKS = [
    "UCT exploitation denominator",
    "UCT exploration coefficient = 25",
    "UCT epsilon = 1e-6",
    "Morgan radius = 3",
    "Morgan bits = 1024",
    "includeChirality = False",
    "self excluded from uniqueness",
    "branching factor = 8",
    "attempts = min(150,5L)",
    "1/2 local mutation = 0.8/0.2",
    "Pure = 100% local",
    "Mixed = 50% local + 50% global",
    "same-length global proposal",
    "fitness formula exact",
    "one child per expansion",
    "first-max tie behavior",
    "child-to-root backprop",
    "no rollout",
    "max expansions = 1000",
    "patience = 150",
    "strict improvement",
]


def run_audit() -> tuple[bool, int, str]:
    config = load_config(REPOSITORY_ROOT / "configs/uct_mcts_manuscript.yaml")
    validate_manuscript_config(config)
    suite = unittest.defaultTestLoader.discover(
        str(REPOSITORY_ROOT / "tests"),
        top_level_dir=str(REPOSITORY_ROOT),
    )
    stream = io.StringIO()
    result = unittest.TextTestRunner(stream=stream, verbosity=2).run(suite)
    return result.wasSuccessful(), result.testsRun, stream.getvalue()


def render(success: bool, tests_run: int) -> str:
    check_status = "PASS" if success else "FAIL"
    final_status = (
        "MANUSCRIPT_EXACT_UCT_MCTS_READY"
        if success
        else "MANUSCRIPT_CONSISTENCY_BLOCKED"
    )
    lines = [
        "# Manuscript MCTS consistency audit",
        "",
        "This file is generated by `python scripts/audit_manuscript_mcts.py` from the frozen YAML validation and the manuscript-exact unit-test suite.",
        "",
        "| Contract item | Status |",
        "| --- | --- |",
    ]
    lines.extend("| {} | {} |".format(item, check_status) for item in CHECKS)
    lines.extend(
        [
            "",
            "Validated unit tests: `{}`".format(tests_run),
            "",
            "Final status: `{}`".format(final_status),
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=REPOSITORY_ROOT / "MANUSCRIPT_MCTS_CONSISTENCY_AUDIT.md",
    )
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    success, tests_run, details = run_audit()
    document = render(success, tests_run)
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != document:
            raise SystemExit("MANUSCRIPT_CONSISTENCY_BLOCKED: audit document is stale")
    else:
        args.output.write_text(document, encoding="utf-8", newline="\n")
    print(details, end="")
    status = (
        "MANUSCRIPT_EXACT_UCT_MCTS_READY"
        if success
        else "MANUSCRIPT_CONSISTENCY_BLOCKED"
    )
    print(status)
    if not success:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
